# Generated by Django 3.2.15 on 2022-08-12 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_placement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='placement',
        ),
    ]
