# Generated by Django 3.2.15 on 2022-08-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
