# Generated by Django 3.2.15 on 2022-08-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='placement',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
