# Generated by Django 3.2.15 on 2022-08-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='goal',
            field=models.TextField(blank=True),
        ),
    ]
