# Generated by Django 3.2.15 on 2022-08-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='placement',
            field=models.BooleanField(default=False),
        ),
    ]
