from django.db import models

board=[
    [2,0,0,0,0,1,0,6,0],
    [9,0,4,0,0,0,0,5,0],
    [0,1,3,5,0,0,0,0,0],
    [0,7,0,0,0,0,0,0,0],
    [4,0,9,7,6,0,0,1,0],
    [0,0,1,9,2,0,4,0,0],
    [0,3,0,0,0,0,0,0,0],
    [7,0,0,0,9,0,8,2,0],
    [0,0,0,2,0,0,3,7,5]
    ]

class Sudoko(models.Model):
    board00 = models.IntegerField(blank=False,null=False)
    board01 = models.IntegerField(blank=False,null=False)
    board02 = models.IntegerField(blank=False,null=False)
    board03 = models.IntegerField(blank=False,null=False)
    board04 = models.IntegerField(blank=False,null=False)
    board05 = models.IntegerField(blank=False,null=False)
    board06 = models.IntegerField(blank=False,null=False)
    board07 = models.IntegerField(blank=False,null=False)
    board08 = models.IntegerField(blank=False,null=False)
    board10 = models.IntegerField(blank=False,null=False)
    board11 = models.IntegerField(blank=False,null=False)
    board12 = models.IntegerField(blank=False,null=False)
    board13 = models.IntegerField(blank=False,null=False)
    board14 = models.IntegerField(blank=False,null=False)
    board15 = models.IntegerField(blank=False,null=False)
    board16 = models.IntegerField(blank=False,null=False)
    board17 = models.IntegerField(blank=False,null=False)
    board18 = models.IntegerField(blank=False,null=False)
    board20 = models.IntegerField(blank=False,null=False)
    board21 = models.IntegerField(blank=False,null=False)
    board22 = models.IntegerField(blank=False,null=False)
    board23 = models.IntegerField(blank=False,null=False)
    board24 = models.IntegerField(blank=False,null=False)
    board25 = models.IntegerField(blank=False,null=False)
    board26 = models.IntegerField(blank=False,null=False)
    board27 = models.IntegerField(blank=False,null=False)
    board28 = models.IntegerField(blank=False,null=False)
    board30 = models.IntegerField(blank=False,null=False)
    board31 = models.IntegerField(blank=False,null=False)
    board32 = models.IntegerField(blank=False,null=False)
    board33 = models.IntegerField(blank=False,null=False)
    board34 = models.IntegerField(blank=False,null=False)
    board35 = models.IntegerField(blank=False,null=False)
    board36 = models.IntegerField(blank=False,null=False)
    board37 = models.IntegerField(blank=False,null=False)
    board38 = models.IntegerField(blank=False,null=False)
    board40 = models.IntegerField(blank=False,null=False)
    board41 = models.IntegerField(blank=False,null=False)
    board42 = models.IntegerField(blank=False,null=False)
    board43 = models.IntegerField(blank=False,null=False)
    board44 = models.IntegerField(blank=False,null=False)
    board45 = models.IntegerField(blank=False,null=False)
    board46 = models.IntegerField(blank=False,null=False)
    board47 = models.IntegerField(blank=False,null=False)
    board48 = models.IntegerField(blank=False,null=False)
    board50 = models.IntegerField(blank=False,null=False)
    board51 = models.IntegerField(blank=False,null=False)
    board52 = models.IntegerField(blank=False,null=False)
    board53 = models.IntegerField(blank=False,null=False)
    board54 = models.IntegerField(blank=False,null=False)
    board55 = models.IntegerField(blank=False,null=False)
    board56 = models.IntegerField(blank=False,null=False)
    board57 = models.IntegerField(blank=False,null=False)
    board58 = models.IntegerField(blank=False,null=False)
    board60 = models.IntegerField(blank=False,null=False)
    board61 = models.IntegerField(blank=False,null=False)
    board62 = models.IntegerField(blank=False,null=False)
    board63 = models.IntegerField(blank=False,null=False)
    board64 = models.IntegerField(blank=False,null=False)
    board65 = models.IntegerField(blank=False,null=False)
    board66 = models.IntegerField(blank=False,null=False)
    board67 = models.IntegerField(blank=False,null=False)
    board68 = models.IntegerField(blank=False,null=False)
    board70 = models.IntegerField(blank=False,null=False)
    board71 = models.IntegerField(blank=False,null=False)
    board72 = models.IntegerField(blank=False,null=False)
    board73 = models.IntegerField(blank=False,null=False)
    board74 = models.IntegerField(blank=False,null=False)
    board75 = models.IntegerField(blank=False,null=False)
    board76 = models.IntegerField(blank=False,null=False)
    board77 = models.IntegerField(blank=False,null=False)
    board78 = models.IntegerField(blank=False,null=False)
    board80 = models.IntegerField(blank=False,null=False)
    board81 = models.IntegerField(blank=False,null=False)
    board82 = models.IntegerField(blank=False,null=False)
    board83 = models.IntegerField(blank=False,null=False)
    board84 = models.IntegerField(blank=False,null=False)
    board85 = models.IntegerField(blank=False,null=False)
    board86 = models.IntegerField(blank=False,null=False)
    board87 = models.IntegerField(blank=False,null=False)
    board88 = models.IntegerField(blank=False,null=False)
